### ISSUE TITLE
[ossia-max] braces notation for models and address discrimination

### ISSUE THREAD

**Issue by vincentgoudard** [ossia/libossia#632]
Hey,

I love the braces notation, but face some of its limitations in the current implementation.
Namely here, I found no way to discriminate addresses when a param is attached to a "multiple" model.

```
<pre><code>
----------begin_max5_patcher----------
2166.3oc0asrjihqDcsquBEr1sGj38rpms2HtwL6mtCGxfrM8EPDH4tpd5n+
2G8.rAavV1.tp6hpbYIDJOGkYpTox5murvZC8MByB76f+FrXwOeYwBUSxFVT
+8EV432hyvL0iYUPdkt4aVK0cwIuwUMSYrT7pRbENmvIU.FMm7m78jp+R1D3
y7eTR.LdUZwNvmSHawGx3fMY38MuohC4oEYDtZVf0Mllne4a91mb7Z8jzC7l
GEU2ptI4znQik0RwOfuV2cIlGuWL4qqHwb8S354txdI.hBW4sD33BkeCgVYC
9pbL+5kWj+Zog7RLMOmTvufXxE.MsLi.xoIjLF.WQ.ETNHIc6VRkXDoXNIAH
XJRyXKqHLQGXdJsXcVZAIldnf2Fra1ESynUZbnja6U9d1Qg1NQHnmenuSuMA
kf6ZD9lCa1jQFZIvs+k.6NClklPZ2ZOLeDTx3dn.4GH2HI.bhZIa52zAFgov
oVDmvEEbRhfiEudvWrTqK.muXY83Diy0Ildnf.GEpcibT5fNdJkO2IV46Rbh
FENQOLN88dt3DNJbBeXbp+X9wINKqAqrQAU6GEpNAAJn5FLJntMiJlYS2E.E
d8cANtAzZRAtF0MPYKsJGqvf+01yXCtX2M12voE98rG01FWc6zJRNkS.hsQ+
qFbYLQE0OQ4b0sKu0VldPTKniPdiB624Ru2GlkdOammzR+uoBe3+JMyc9sGR
OveF0CbihlB8fg71UVQEqi4h+7GzCfXbgNtIVbUp.zhvl.utGy0AVARYfXZQ
LopPDMUyq5CTvSH262Qan1LSvxx3jr8z1dyPbR4hMUv6HCseys8.g5AvCDr.
bPMuqpw4n87XGpnjQZ5cmddr+v34w0O5464A8XddfyomG+nm+NPvONAeTGm4
yUO.9P5AP64TOvYRzCFfHJqROsszMw4i6fOvSkABz3vvg7M2wpRviqKOJMWD
zUc3e6mHXCeuvZPzTfUyx3Vaay57sIzdOkrMHxwXkC3zmqMMg3Fn0zilEyUv
NBecgfBXk3XhwApLkwoDnymSj1VNz+DNaOFRUM5pgmX+gzLx2IUrTZQqIegE
trrUyKZMDIm7McXrgKO1TZgtIzwlpHeOsY71GaEWIjbtPrOTovk0a9M9ujuF
g69phCoGimTs5TKRp0gSrrbvxkqlta4i1VAecJtb7Ue3KihsgLjwhmQi+ejj
1BmEsjTjVzNKnc5tVgd8VZAmk9O5.tk7cO8usVB6sSIFTh+eTkhyNBfcUoIz
BoPzYkP1byzIN2fNeVc.i5IJvk8LXgdlfVFnSl.jGXavUxEpZ+OMqeVbJMqa
WGGWFYKut6xzhhyXQNsb3NqR2s+JicCUzY90d2pdXqOTn6csPmfulg+dW1li
yxpMV695eCWjJhGhvS0KAH6icp8AuWbJOZVVG7p6468zShPGOl7ZZBeuZhZq
LHOtXYiRj0wU4jzcDFuaab7NV2VX7enI8VMcXSsM7ZNIuLSfhtOfv5HkwY6o
uxpevFEs1DvoacosMcaOecZ+pGXqqav3LBtRlfv181mSvycDFc1.tzY3MbHN
jSQnv12S5Ur2zlrnYCfZ2LOHkzYSgyiiiHr4R.LBW9yf7BredIXt3Ejmq9pm
rO4m78fWf2Ki3OaLhusJWGQJ2q9dOaF4ex.rLgqjqPICX73MLkftJkrz.ZwA
1D1jzLx98z.5dUUPylSEOMoDotE2.2YgSTvaPHa2OjgyEj87UH1WmIrle2YT
M4Rs8NRJwqHg7Vqv4laMFNHCr4d0UbfivHpygxFjA0lN02f0+WYGENWZUtty
ucjAbh8cyHy19xvP365tPiLdEj+b6y88JfEAc.1.9zcGuB5J6N6Xjikkx8B3
2lfzI3HR4h1O3YyOp655Xdwtjd7FfdbGldbuF8nRO5oL1ZDCEo1Dq1ErO7YS
QUBPP.mmjHiCyCNqw4o2dBVWXZ1Nebhowwc17oTmSvQEUCZB4GMDt6XWthhg
8MhtOPmkXzTGW2oTSIuH7AR3fRfj82O0vnGphaVLqitEzU1RHLt793qywxee
xRAXpl6cKDdFJENvYTJPlJDyIUHcdajTHiW5rGjVknSEM78Uz7GVxrmGISth
fLgzjPvYtV5jRAz.oHZN0e7MU+IbNkh.SkB+4TJB+HXQq7YAMU4bVkBS3hYk
JL141bJElZlhlYY3c2J0TWEAynLXrihYTFhFuah5FatVUK4cmkrVeOgqwbdU
5FwAUXmeOw208YsKitAmc1kP020c8xIgahpbv69V3cl9agOTk3l.mQUqAeKk
uJljksQdQ0MxXqam7TAdcwsMeSLOPEMWejaQL+YcFY+W38kTSVJqywxOQUh2
3wKIE41Vz68tvGlZQH8w0P5zEFF1pBGpnupS1f8oYMgrUObw48Dm52eo7Cac
s217KUp.Fn4OAa9A70ouHZzUP7oBc6mvUqb9krzYNZrA9h0e.psjXfDh3MWQ
R.XF.qK.4uXA9rzfBHl18jrRwyjS6sNjcLrJbBdXKhV02r8JHxyMRxkAQ91A
gx+JLxEBC6VQyCWKKN503f5R99L6H0Kn64K0qGm6SsdU4xXt53L0fc0tXk23
YJzjYJZJlIOSlI+oXl7MYl7lfYB1IpzglITmGp64Ke3o1wDL1YhySSJooE7Z
cxPj5hSQ0YuN532tTRsG2xgARZWcidkTjt.4Z8kQt3EXHCN14wjUptxxDohH
qx3aNyvovKBzDuHMhy3TlLASH3TLSPSlI6mkWDna+pHiy1DZhQ.DNUf7Vyzk
5h5sROqhOkywYU54YU44kU34vU244U1o53G5pb6rsuOFP3+AmSywq2mtS.8c
64xSoTgKZh4uohJ6RI33XRA+x+Oq7NETWCzWVSsx+W3Oub6z+2y2rz2vPCT.
pu7qW9Wv5brAK
-----------end_max5_patcher-----------
</code></pre>
```

**Comment by avilleret** [comment]
thanks for raising that one. 
this is exactly what I needed when I opened #630.

Until now, ossia object should return an address of the same type as their `address` attribute and relative to their parent.
It seems to work but leverage this issue.

So how should we output the address in this case ? should we output a global address ?
Then should we do that always ? 
Actually the address in trimmed only for convenience, if it doesn't work then we should change it.

**Comment by bltzr** [comment]
How about this ? 

<pre><code>
----------begin_max5_patcher----------
2504.3oc6bs0iipiD94z+J7xyY5C1beeX0LZeak1ybzJsZ0poGE4DbmvrbIB
blomyn4+9wW.BPfzlN.gyJdH2rAbUetpxkKWU9wCqz1l7BISC7WAeBrZ0OdX
0JQS7FVk+6UZQ3W1EhyDWlVL4aIa+h1ZYWTxKTQyGSChof+UQ6wmhBhCITw8
.yaLvWbora+cHiJWYxIZwkpm2ZF86gDwUWbcGwzcGBh2uIkriJIXaWqG0WCr
rfOZsFXZy+AB8nN3y7a4mO7.+s02HeA1SnahwQjri3cjV4Ozk7GrjrSIYjXJ
lFjDWgzg55PA4Z3x+PO+MvmaEUfchJxKh98iD4yUSq7QzBfcdTs3HFxsBjU8
tHo4.UNRsR64fPxWIoYLtnBAsRCe7XklWU4V3v6WRDOHm0kMEDKaxnroTxWC
JteqxVwoLZmxH7SoRF9EaSsyOlDeRZ7o.AoHajMQ+PwCrfcszE7mmA+cCawG
15Vm4VlLw9vjc+OheEYOFndjDGDWclqV29jmwmBoadNIllE76B5Cxvv15+Yt
LSW2LWpRvbeHM.GVvdZ6SC7Sh4DQMnl2bwvwlJEh9vZLi3JhwGa4lYxjLXoi
NyXL4ors3T9LwVoDFpnSZRRX8tJuuPxyz7tOFDG2.EoIG6tyzf8Gtx8tMg0Y
z0d1hdx1bJV16FldLcSF9q0QaJNLLWwt9i+EbbPDlRnAxo.jdYmjXLiQOjsK
MILrF+J64qsziOSHdG4aA9zChAppv.6xCNVHDoUNK6GrmjQq2FEuOqdKWnwy
Z5z1bkzMTRzwPFWT+BpYRupFYUSf0ZugoPlstL7dRo9VU6g6BI3T.CVq1aaV
CaZQzqwMbo4sNX3qalqSScL0clINnT42Ru9ZCqJVeH2zwaDnpslQy0CIL0Le
PFgxe0IZAaGsblVzBYYxQKCS8yFLuGnEru3j8DiS15hEN8DVesslZb52CAYg
LKMWAn5P8ypafB8F.p0J.VFB2xLPdBEQ86oJXeEqPSrwJoGrFdlbLxwbTPJA
S2IPn2NP.mVfvxVfCB21LzKdu1csKIJh4V1ECVPrO4kJNDN1RWTPHXaekqLf
CtZ3Vb79WGWkJeFdmA1+rnI5NsRflliulnBHkduwoI1iAnK7ttR3M5eEx99X
g+d4fECj.aAuq29WgtheCF2fAq070inuNrY5vgMOwBB1NSMpsK4TLkj1InY0
AnY1MnY1ePiCTqy84RUbySrPZtAea3TCboLlf.ZF0LkcVEdG7VUtDIzRXxGp
aLe7AyvbhsUIU5tMuvPCHpIYgd6q0UDhzeUXqs8yHfEKczP6c54H3EFD2Una
DDDu+1ArrjSo6Jlhy8bGTm17IYzf3x3Y9oy5Z.Ukx6MQXoHUX.GQp.oJQLlP
AeQAknBtmbMtvjTeYH4g2WRytaJSebnL9LBREPiyBFi0TGmJfJPEdio7ispx
OtiIU3nJUXOlTg6bPiVXyBppv4nREpfEiJTnrwswjJTUMEMxzvcWKUUSENiH
MnrghQjF7tcyD4MVb7xZ7iXzei73T2fozzfsrs5j077x60w9sOLYKNL+P8JO
T3qcFfmOnvGNSu8LgGpeJem26Vuy0ASEy0AnA7NjqCPjK2scGiaJ6P9R.8wc
jvvs7zEnffRS9lLL.5JhTEAcRqyS+Wqx4NqqXJj3fT.Vyi6.aCJgkGSMxT+b
q0n4Kf5vfrZAg3Lz2RVNb0TOw1SdpPxPq55VghaOgJ3DmO4Y4ig8fVCrsWy+
PuJayZQ7V6M+NXwKvmGxrCJIKK.qZNO4oMMB7Nxsu6cQt8v.RY127IFz.QVl
dbLxwyV2wk+MWOSHzU.YCNH83QbJSfmRRAYIQjORYl59MdSf2yYPPFyRZ7dv
6yyOFv1P7AUA1xc52dnhTBYW+JnqYdfgjVSLLg2j4jhvDzDphXrdvwPBfmgS
gY.bJADmPA9AO+LIkcGAXJwGvvNhxfSo44s6qH.jaJ11R2ysxWfcZ.o6Lya6
os0yLn1vOOQ7usPBYSjo7fn7pLZxmRVfOob6jCDnh88YVPyHYfmDYNVHv3IM
kgudmnhJAGNR0SS4IA.Mjmeh4.KNcImi5AmiFUNWdjQSGmC6AmCGUNW9w3y4
3vvBtOqGLu9Xx7FNhCwgGh4ag4eNLgQcJmrwtm86JMBKnH6RRMeYoMxr6qJq
dSqlT6b4aeEEiJHRyLTaHW5MkDkPI.1Rt+VA2pLz0gSKF8bo0Wa4UKHpBXfP
V2DZzSwCqYr3gktwDId7KBmO9mbyEF+xaRVwdRkUL87FBYktridLMgMeGw95
2SNA1gik9gw2VeDOBBDv2NfoRG0.AYfcIw6X6dm4c1Swu6uA90O9e.+2O9uA
+8O7qf+RwCmG5BwYJWEVdUXcd3.mia9IdI8fSWT2BVu0sJzUvGxW8BzKYwV1
oMBMta1xRJ0YfDhhnaT8rm1qzmw1qLs8ld6Un2l8J3zZux1a5WaCNmc8I2S3
oUVA9ljUf5SqrhwfHqbsZ0SYN2b.pTOWCY3WcxC92swUmh11iYNGs4h7NBZJ
yfjIj8cmObubxeL01OGiwJJ7+.93iF+rlVedLG4UrZY.Gg0JI0qKRAmh3MJA
s7bwxy75QykG4VGagefd5POw2f4A1ENKpH1Q1gL446.8jlVVJr0kBacovVWJ
r0kBacovVWJr0kBacovVWJr0kBacovVWJr0kBacovVWJr0kBacovVWJr0kBa
covV+yWgs5MGp8q4P0sLGpxmYQ4NMGp6q4QEvMOJFvYQcQNOpQzYR8xNOpc3
YQYTOOpn74aE2Oi+aJXNnPOO9GsX.9y8XovVe0TVvXJRYA4+g4yhxS05MUdp
yq5Ls.Hk6w6+ipxzGkYZdy7Zhm.SkZjfmz9.HWcKC3SXO4ThO.mAvxDU+IMv
64pX.1vdfDdjcMQI2T1o6LIo0igYkJc1za.poUwCn91RkyPMMEmOOcoI3Zd4
10hjnZWT8EHuP3XPGZXsExa31vaenqspeWCckk9tMl70FI214Q33OxiC7xK2
pydm1kPkw..uhQBNEijoBno2XLO5oxz3Dwf00XiB7OlDDSyJpbenH6Kf40DK
RVA+heN3JvJPr01zQWDK2XrH8Gp7yaUlTEhiW8K2tzutJizfXFyUEoigfmfp
vSP2AXjLTXfbFCMZUV7AMDhGJLNVWSIwUnafPhSopxOl.fGcMKMRRAhxOyVu
xeM3KjYqBoZMDyUVpLR1CwHohpLxanVb9UGoKUkkN01H004CRiTVuQ5peYpp
2cZp2LE0EwOP5leCGoK2.4+.GkDg2bHXOi22efxCyPJNtXG5EYNdcLAuaGIl
dY8tZcdCWEr95brk++iRy8aH+GUoPdVD0ie9venuk42A
-----------end_max5_patcher-----------
</code></pre>

**Comment by vincentgoudard** [comment]
I guess the trimmed address is more user-friendly (in terms of interface) and the full path more useful and coder-friendly. 
Now the thing is, you can trim the adress after the object (with regexp), but you cannot know which is the model corresponding to what you receive (in the case you target a specific one with ossia.remote).
So my personal preference goes for the "coder-friendly" version.

**Comment by bltzr** [comment]
what about a `@trim_address`attribute, that would default to 0 for user-friendliness first ?

**Comment by vincentgoudard** [comment]
@bltzr  I was to propose the same. Get my vote!

**Comment by bltzr** [comment]
excuse me, yes, defaults at 1

**Comment by bltzr** [comment]
meanwhile, I guess you could work this around with my proposal above, couldn't you ? (untill "all bugs are fixed")

**Comment by vincentgoudard** [comment]
maybe, the drawback of having to explicitely write the full path is that the model needs to retrieve its parents name recursively. But it's possible yes... That's why we call it a "work around" I guess... :))

**Comment by avilleret** [comment]
ok for the `@trim_address` attribute, that should not be too hard to do

**Comment by vincentgoudard** [comment]
The `@trim_addr` is there, but AFAIC, I am still getting "address theParameter" as output in the patcher above.... :'(

**Comment by vincentgoudard** [comment]
The issue seems to be that it works when you put the argument in the object, but not when you change it with a message, or attrui object, nor with the inspector.
The attr_address is also not showing up in the list of attributes when you type the object name with Max's "Options/Assistance" enabled.
